name: env-cgan
channels:
  - conda-forge
dependencies:
  - jupyter
  - python
  - pyvista
  - matplotlib
  - numpy
  - pytorch
  - tqdm
  - tensorboard
prefix: /rwthfs/rz/cluster/home/vi113507/miniforge3/envs/env-cgan
